Robot_localisation:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true

    use_sim_time: true

    # GPS Parameters
    navsat0:
      topic: /gps/out
      frequency: 10.0
      differential: false
      position_covariance: [0.5, 0.5, 1.0]
      yaw_offset: 0.0
      static_covariance: [0.5, 0.5, 1.0]
      dynamic_covariance: [0.5, 0.5, 1.0]
