version: "3.8"

services:
  exomy_sim_humble_gpu:
    build: .
    privileged: true
    container_name: exomy_sim_humble_gpu
    volumes:
      - ../../ExoMy_Software/exomy:/home/exomy/exomy_ws/src/exomy
      - ../../ExoMy_Software/exomy_msgs:/home/exomy/exomy_ws/src/exomy_msgs
      - ../exomy_sim:/home/exomy/exomy_ws/src/exomy_sim
      - ../exomy_sim_msgs:/home/exomy/exomy_ws/src/exomy_sim_msgs
      - ../exomy_sim_launch:/home/exomy/exomy_ws/src/exomy_sim_launch
      - ../rover_gazebo_plugins:/home/exomy/exomy_ws/src/rover_gazebo_plugins
      - type: bind
        source: /dev
        target: /dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    ports:
      - "8000:8000"
      - "9000:9000"
      - "8080:8080"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all  # Ensures all GPUs are visible
      - NVIDIA_DRIVER_CAPABILITIES=all  # Required capabilities for ROS2 and Gazebo
    runtime: nvidia  # Specifies the use of NVIDIA runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
